### ISSUE TITLE
Permission bug when swapping from API level 26 to API level 30.

### ISSUE THREAD

**Issue by zalexchen** [WSU-4110/WarriorSocial#58]
ERROR: java.lang.SecurityException: Permission Denial: opening provider com.android.providers.media.MediaDocumentsProvider from ProcessRecord{1991732 5945:com.example.warriorsocial/u0a154} (pid=5945, uid=10154) requires that you obtain access using ACTION_OPEN_DOCUMENT or related APIs

Reasoning: Likely something to do with depreciation of old functions or some newer permission scheme introduced in later API's?

**Comment by ChloeMJM** [comment]
Seems to only occur when testing on certain devices. Running emulation with API 26 is fine, running any emulator that uses API 30 will create this error. 

This line in the error seems to point at OrganizationProfile.java file, line 186:
at com.example.warriorsocial.ui.organizations.OrganizationProfile$4.onDataChange(OrganizationProfile.java:186)
