### ISSUE TITLE
Change Password Issue

### ISSUE THREAD

**Issue by RichSosa28** [WSU-4110/WarriorSocial#60]
Getting an error when trying to send password reset link to user email.
In order to reproduce this issue:
1. Register/Login with an account.
2. Navigate to the settings page and click "change password".
3. Enter in associated email to receive reset link.

**Comment by ChloeMJM** [comment]
I tested it and I'm getting the same error. As soon as I hit "yes" on the alert dialog for password reset, app crashes. Let me know if you find a workaround for this.

**Comment by RichSosa28** [comment]
Was able to fix this issue. Closing now!
